"""OWASP Top 10 Checklist Generator — hybrid approach.

Hardcoded OWASP Top 10 (2021) categories + local LLM via Ollama
for contextual per-category recommendations.
"""
import json
import logging
import requests
from flask import current_app

logger = logging.getLogger(__name__)

# OWASP Top 10 (2021) — authoritative data, never generated by the LLM
OWASP_TOP_10 = [
    {
        "id": "A01",
        "category": "Broken Access Control",
        "severity": "Critical",
        "description": (
            "Restrictions on what authenticated users are allowed to do are often "
            "not properly enforced. Attackers can exploit these flaws to access "
            "unauthorized functionality and/or data."
        ),
    },
    {
        "id": "A02",
        "category": "Cryptographic Failures",
        "severity": "Critical",
        "description": (
            "Failures related to cryptography which often lead to sensitive data "
            "exposure. This includes use of weak algorithms, insufficient key "
            "management, and transmission of data in clear text."
        ),
    },
    {
        "id": "A03",
        "category": "Injection",
        "severity": "Critical",
        "description": (
            "Injection flaws such as SQL, NoSQL, OS, and LDAP injection occur when "
            "untrusted data is sent to an interpreter as part of a command or query. "
            "Hostile data can trick the interpreter into executing unintended commands."
        ),
    },
    {
        "id": "A04",
        "category": "Insecure Design",
        "severity": "High",
        "description": (
            "Risks related to design and architectural flaws. Insecure design cannot "
            "be fixed by a perfect implementation — the security controls were never "
            "created to defend against specific attacks."
        ),
    },
    {
        "id": "A05",
        "category": "Security Misconfiguration",
        "severity": "High",
        "description": (
            "The application is missing appropriate security hardening, has improperly "
            "configured permissions, unnecessary features enabled, or default accounts "
            "and passwords left unchanged."
        ),
    },
    {
        "id": "A06",
        "category": "Vulnerable and Outdated Components",
        "severity": "High",
        "description": (
            "Using components with known vulnerabilities, including libraries, "
            "frameworks, and other software modules running with the same privileges "
            "as the application."
        ),
    },
    {
        "id": "A07",
        "category": "Identification and Authentication Failures",
        "severity": "High",
        "description": (
            "Application functions related to authentication and session management "
            "are often implemented incorrectly, allowing attackers to compromise "
            "passwords, keys, or session tokens."
        ),
    },
    {
        "id": "A08",
        "category": "Software and Data Integrity Failures",
        "severity": "High",
        "description": (
            "Code and infrastructure that does not protect against integrity "
            "violations, including insecure CI/CD pipelines, auto-update mechanisms "
            "without integrity verification, and insecure deserialization."
        ),
    },
    {
        "id": "A09",
        "category": "Security Logging and Monitoring Failures",
        "severity": "Medium",
        "description": (
            "Insufficient logging, detection, monitoring, and active response. "
            "Without these, breaches cannot be detected in a timely manner and "
            "attackers can pivot, extract, or tamper with data."
        ),
    },
    {
        "id": "A10",
        "category": "Server-Side Request Forgery (SSRF)",
        "severity": "Medium",
        "description": (
            "SSRF flaws occur whenever a web application fetches a remote resource "
            "without validating the user-supplied URL, allowing an attacker to coerce "
            "the application to send a crafted request to an unexpected destination."
        ),
    },
]

# App type keywords for better prompt context
APP_TYPES = [
    "Web Application",
    "Mobile Application",
    "REST API",
    "Desktop Application",
    "IoT Device",
    "Microservices",
    "E-Commerce",
    "SaaS Platform",
]


def _call_ollama(prompt: str, timeout: int = 30) -> str:
    """Call local Ollama instance and return the generated text."""
    ollama_url = current_app.config.get("OLLAMA_URL", "http://localhost:11434")
    model = current_app.config.get("OLLAMA_MODEL", "qwen2.5:0.5b")

    try:
        resp = requests.post(
            f"{ollama_url}/api/generate",
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.4,
                    "num_predict": 120,
                    "top_p": 0.9,
                },
            },
            timeout=timeout,
        )
        resp.raise_for_status()
        return resp.json().get("response", "").strip()
    except requests.RequestException as exc:
        logger.warning("Ollama call failed: %s", exc)
        return ""


class OwaspService:
    """Generate OWASP Top 10 checklists with contextual AI recommendations."""

    @staticmethod
    def generate_checklist(app_name: str, app_type: str) -> dict:
        """Build a full OWASP Top 10 checklist with AI-powered recommendations.

        1. Iterate the hardcoded OWASP Top 10 list.
        2. For each category, ask the local LLM for a short, app-specific
           recommendation (1–2 sentences).
        3. Assemble the final JSON in Python — never ask the LLM to produce JSON.
        """
        from datetime import datetime, timezone

        checklist = []

        for item in OWASP_TOP_10:
            prompt = (
                f"You are a cybersecurity expert. "
                f"For an application called \"{app_name}\" which is a {app_type}, "
                f"write exactly ONE short paragraph (2-3 sentences) with a specific, "
                f"actionable security recommendation for: "
                f"{item['id']} {item['category']} — {item['description']}. "
                f"Be specific to this application type. Do not repeat the category name."
            )

            recommendation = _call_ollama(prompt)

            # Fallback if LLM is unavailable or returns empty
            if not recommendation:
                recommendation = (
                    f"Review your {app_type.lower()} for {item['category'].lower()} "
                    f"vulnerabilities. Implement appropriate controls and conduct "
                    f"regular security testing."
                )

            checklist.append({
                "id": item["id"],
                "category": item["category"],
                "severity": item["severity"],
                "description": item["description"],
                "recommendation": recommendation,
                "checked": False,
            })

        return {
            "app_name": app_name,
            "app_type": app_type,
            "checklist": checklist,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    @staticmethod
    def get_app_types() -> list[str]:
        """Return supported application types."""
        return APP_TYPES
